### PR TITLE
make format an option

### PR DESCRIPTION
**Pull request by gingur**

### CODE REVIEW

**Comment by gingur** [comment]
@GitaiQAQ do you have any issues with this update?

**Comment by GitaiQAQ** [comment]
You need to be customized for input source formats in the conversion method? So use the option.format to do this? 

But the option.format to change the option.output.format is not easy to understand. 

Maybe option.output._format or flip option.output.transform and option.output.format is batter. like this

```js
const _format = outputOptions.transform || 'amd';
outputOptions.transform = outputOptions.format;
outputOptions.format = format;
```

**Comment by gingur** [comment]
Sorry @GitaiQAQ I don't quite understand your response, nor do I remember why I needed this functionality originally. The gist of the PR is to make `outputOptions.format` configurable, as you currently have it hardcoded to `amd`.  Feel free to close this PR if you don't think that should be an option.

**Comment by GitaiQAQ** [comment]
Ok, I will close this PR.

**Pull request closed without merging**
